
SELECT (
    SELECT NVL(SUM(BS.BLOCK_SIZE),0)
    FROM {{.Owner}}.BLOCKS BS
    WHERE BS.BLOCK_NAME IN (SELECT TOKEN FROM TOKEN_GENERATOR)
) AS FILE_SIZE,
(
    SELECT NVL(SUM(BS.FILE_COUNT),0)
    FROM {{.Owner}}.BLOCKS BS
    WHERE BS.BLOCK_NAME IN (SELECT TOKEN FROM TOKEN_GENERATOR)
) AS NUM_FILE,
(
    SELECT NVL(SUM(FS.EVENT_COUNT),0)
    FROM {{.Owner}}.FILES FS
    JOIN {{.Owner}}.BLOCKS BS ON BS.BLOCK_ID=FS.BLOCK_ID
    WHERE BS.BLOCK_NAME IN (SELECT TOKEN FROM TOKEN_GENERATOR)
) AS NUM_EVENT
FROM DUAL
