SELECT CD.DATASET child_dataset,
       CD.DATASET_ID child_dataset_id,
       D.DATASET
FROM {{.Owner}}.DATASETS CD
JOIN {{.Owner}}.DATASET_PARENTS DC ON DC.THIS_DATASET_ID = CD.DATASET_ID
JOIN {{.Owner}}.DATASETS D ON  D.DATASET_ID = DC.PARENT_DATASET_ID
