SELECT DISTINCT PDT.PRIMARY_DS_TYPE_ID, PDT.PRIMARY_DS_TYPE AS DATA_TYPE
FROM {{.Owner}}.PRIMARY_DS_TYPES PDT
{{if .Dataset}}
JOIN {{.Owner}}.PRIMARY_DATASETS PDS on PDS.PRIMARY_DS_TYPE_ID = PDT.PRIMARY_DS_TYPE_ID
JOIN {{.Owner}}.DATASETS DS ON DS.PRIMARY_DS_ID = PDS.PRIMARY_DS_ID
{{end}}
