INSERT INTO {{.Owner}}.FILES
(FILE_ID, LOGICAL_FILE_NAME, IS_FILE_VALID,
DATASET_ID, BLOCK_ID, FILE_TYPE_ID, CHECK_SUM, EVENT_COUNT, FILE_SIZE,
ADLER32, MD5, AUTO_CROSS_SECTION,
LAST_MODIFICATION_DATE, LAST_MODIFIED_BY)
