SELECT P.PRIMARY_DS_ID, P.PRIMARY_DS_NAME, 
       P.CREATION_DATE, P.CREATE_BY, PT.PRIMARY_DS_TYPE  
FROM {{.Owner}}.PRIMARY_DATASETS P
JOIN {{.Owner}}.PRIMARY_DS_TYPES PT ON PT.PRIMARY_DS_TYPE_ID = P.PRIMARY_DS_TYPE_ID
