SELECT MAX(LUMI_SECTION_NUM) AS MAX_LUMI FROM {{.Owner}}.FILE_LUMIS FL
{{if .Dataset}}
JOIN {{.Owner}}.FILES FS ON FS.FILE_ID=FL.FILE_ID
JOIN {{.Owner}}.DATASETS DS ON FS.DATASET_ID=DS.DATASET_ID
{{end}}
