{{if eq .Owner "sqlite"}}
SELECT DATASET_ACCESS_TYPE
FROM DATASET_ACCESS_TYPES
WHERE DATASET_ACCESS_TYPE = ?
{{else}}
SELECT T.DATASET_ACCESS_TYPE
FROM {{.Owner}}.DATASET_ACCESS_TYPES T
WHERE T.DATASET_ACCESS_TYPE = :dataset_access_type
{{end}}
